
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course_system?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

  rabbitmq:
    host: 43.138.171.179
    port: 5672
    username: guest
    password: guest

server:
  port: 9010